name: Build and publish NODE images.

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build_node_images:
    uses: ./.github/workflows/reusable-build-and-push-image.yml
    secrets: inherit
    strategy:
      fail-fast: false
      matrix:
        include:
          - title: node16-ubi9
            dockerfile: 16-ubi9.dockerfile
            tags: |
              type=raw,value=16-ubi9
              type=raw,value=16-ubi9-{{date 'YYYYMMDD'}}
          - title: node18-ubi9
            dockerfile: 18-ubi9.dockerfile
            tags: |
              type=raw,value=18-ubi9
              type=raw,value=18-ubi9-{{date 'YYYYMMDD'}}
          - title: node20-ubi9
            dockerfile: 20-ubi9.dockerfile
            tags: |
              type=raw,value=20-ubi9
              type=raw,value=20-ubi9-{{date 'YYYYMMDD'}}
          - title: node21-ubi9
            dockerfile: 21-ubi9.dockerfile
            tags: |
              type=raw,value=21-ubi9
              type=raw,value=21-ubi9-{{date 'YYYYMMDD'}}
          - title: node22-ubi9
            dockerfile: 22-ubi9.dockerfile
            tags: |
              type=raw,value=22-ubi9
              type=raw,value=22-ubi9-{{date 'YYYYMMDD'}}
          - title: node23-ubi9
            dockerfile: 23-ubi9.dockerfile
            tags: |
              type=raw,value=23-ubi9
              type=raw,value=23-ubi9-{{date 'YYYYMMDD'}}
    with:
      image-name: pfaffk/node
      build-context: ./node
      dockerfile: ${{ matrix.dockerfile }}
      image-title: ${{ matrix.title }}
      tags: ${{ matrix.tags }}
            